# Generated by Django 3.1.5 on 2021-02-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210208_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
