# Generated by Django 3.1.5 on 2021-02-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_post_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
