# Generated by Django 3.1.5 on 2021-02-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_post_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='classname',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
