# Generated by Django 3.1.5 on 2021-03-30 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20210308_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quarter_taken',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='classNumber',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F'), ('CREDIT', 'Credit'), ('NO CREDIT', 'No Credit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='teaching_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
