# Generated by Django 3.1.5 on 2021-03-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210330_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year_taken',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
