# Generated by Django 3.1.5 on 2021-05-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0002_auto_20210521_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmodel',
            name='status',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
