# Generated by Django 3.1.5 on 2021-05-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0003_ipmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='status',
            field=models.CharField(default='like', max_length=7),
        ),
    ]
