# Generated by Django 3.1.5 on 2021-05-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0004_auto_20210524_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='status',
        ),
    ]
